on: [push]

jobs:
  add-calver:
    runs-on: ubuntu-latest

    name: Add a calver tag

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Hello
        uses: actions/hello-world-docker-action@master
        with:
          who-to-greet: "Mona the Octocat"

      - name: Add a tag
        uses: peterkimzz/actions-test@main

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: "#eventcat-notifications-test"
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.message }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      # - name: Send a notifiation
      #   uses: slackapi/slack-github-action@v1.23.0
      #   with:
      #     payload: |
      #       {
      #         "commit_message": ${{ toJSON(github.event.head_commit.message) }},
      #         "preview_url": "https://mediacat-qa.xl8.ai",
      #         "deployment_mode": "Hotfix QA"
      #       }
      #   env:
      #     # Slack workflow builder name: Hotfix Deployment Alert
      #     SLACK_WEBHOOK_URL: https://hooks.slack.com/workflows/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
